name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

   # - name: Run tests
    #  run: npm run test:headless

    - name: Build
      run: npm run build:prod

    - name: Debug Permissions
      run: |
        echo "Current repository: $GITHUB_REPOSITORY"
        echo "Current actor: $GITHUB_ACTOR"
        echo "Token: ${{ secrets.GITHUB_TOKEN }}"
        git remote -v
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/souq-today
        enable_jekyll: true
